export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";

export const IS_CREATE_MODAL = "IS_CREATE_MODAL";
export const CLEAR_CREATE_RESPONSE = "CLEAR_CREATE_RESPONSE";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";

export const GET_CATEGORIES = "GET_CATEGORIES";
